name: Docker Image
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: echo "🎉 Test de la secret vraiment secret ${{ secrets.REGISTRY_USER }} event."
    - name: test env
      run: env
      env:
        REGISTRY_USER_ENV: ${{ secrets.REGISTRY_USER }}
  applications-test-units:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.17'
        check-latest: true
    - run : echo "🎉"
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17' ]
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: build/Dockerfile
        push: true
        tags: |
          ${{ secrets.REGISTRY_USER }}/dns-updater:unstable
